version: '1'

services:
  db:
    image: postgres:14.2-alpine3.15
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: authserver
    ports:
      - "5432:5432"


